### ISSUE TITLE
m2m `through` relationship queries return wrong result

### ISSUE THREAD

**Issue by rjauquet** [charettes/django-seal#34]
Given a many to many field with a through relationship where one model is sealed:

```
class AQuerySet(SealableQuerySet):
    ...
class A(SealableModel):
    objects = AQuerySet.as_manager()
    bs = models.ManyToManyField(
        B,
        blank=True,
        related_name='a_b',
        through=AB,
    )
class B(Model):
    ...
class AB(Model):
    a = models.ForeignKey(
        'A',
        related_name='+',
        on_delete=models.CASCADE,
    )
    b = models.ForeignKey(
        'B',
        related_name='+',
        on_delete=models.CASCADE,
    )
```

Then using the `through` relationship will produce incorrect results where a query directly on the model will produce correct results:

```
# before new relation added
a_instance.bs.count() # 0
AB.objects.filter(a=a_instance).count() # 0

AB.objects.create(
 a=a_instance,
 b=b_instance,
)

a_instance.bs.count() # 0
AB.objects.filter(a=a_instance).count() # 1
```

This behavior does not happen when `AQuerySet` is a regular `QuerySet` class.

**Comment by bryanhelmig** [comment]
What was the resolution here?

**Comment by charettes** [comment]
@bryanhelmig it ended up not being related to django-seal after all.

**Comment by rjauquet** [comment]
@charettes and I being silly. It's cached and should be cached. From what I gather, there isn't an official API to bust the cache though. Definitely not a seal issue.
