### ISSUE TITLE
Prefetching a relationship and then a relationship across the first relationship breaks

### ISSUE THREAD

**Issue by fish-face** [charettes/django-seal#39]
```python3
test = MyModel.objects.all().prefetch_related('a', 'a__b')
for x in test:
    pass
```
Results in `ValueError: 'a' lookup was already seen with a different queryset. You may need to adjust the ordering of your lookups.`

I believe, from reading another issue, this is due to prefetches being resolved into explicit `Prefetch` objects, so it should just involved some de-duping.

Note that I *believe* that in the absence of `django-seal`, both prefetches are necessary if you want to avoid extra queries when looking up information on `b`.

**Comment by charettes** [comment]
Thanks for the report.

> Note that I believe that in the absence of django-seal, both prefetches are necessary if you want to avoid extra queries when looking up information on b.

I'm confirm the opposite. `.prefetch_related('a', 'a__b')` can be reduced to `.prefetch_related('a__b')` and will cause both prefetches to occur just as if `prefetch_related('a', 'a__b')` had been specified.

**Comment by charettes** [comment]
Here's a regression test for this crash, didn't managed to come up with a complete solution so far

```diff
diff --git a/tests/test_query.py b/tests/test_query.py
index 0916aad..b4565b8 100644
--- a/tests/test_query.py
+++ b/tests/test_query.py
@@ -315,6 +315,22 @@ class SealableQuerySetTests(TestCase):
         ).seal().get()
         self.assertSequenceEqual(instance.location.climates.all(), [self.climate])

+    def test_prefetch_combine(self):
+        instance = SeaLion.objects.prefetch_related(
+            'location',
+            'location__climates',
+            'location__previous_visitors__location',
+            'location__previous_visitors__previous_locations',
+        ).seal().get()
+        Prefetch('location', queryset=Location.objects.prefetch_related(
+            Prefetch('climates', queryset=Climate.objecs.seal()),
+            Prefetch('previous_visitors', queryset=SeaLion.objecs.prefetch_related(
+                'location',
+                'previous_locations',
+            ).seal()),
+        ).seal())
+        self.assertSequenceEqual(instance.location.climates.all(), [self.climate])
+

 class SealableQuerySetInteractionTests(SimpleTestCase):
     def test_sealed_select_related_disallowed(self):
```

**Comment by fish-face** [comment]
I have double-checked and you are quite right that this is in fact unnecessary in vanilla django.
