### ISSUE TITLE
Doesn't work with foreign key

### ISSUE THREAD

**Issue by renetta96** [charettes/django-seal#56]
The lib doesn't seal the {foreign key}_id of ForeignKey relationship. When I access that attribute, it triggers a query to database, even though the queryset has `.only('pk').seal()` .

When I check the class attribute, normal attribute and foreign key attribute like this are different:
one is <django.db.models.fields.related_descriptors.ForeignKeyDeferredAttribute object at 0x7fffeff3b8d0>
other is <seal.descriptors.SealableDeferredAttribute object at 0x7fffeff2ac10>

**Comment by charettes** [comment]
Thanks for the report. This was caused by the introduction of `ForeignKeyDeferredAttribute` in https://github.com/django/django/commit/4122d9d3f1983eea612f236e941d937bd8589a0d.

I'll work a PR this week.

**Comment by charettes** [comment]
Should be fixed in 1.4.1 which was just released https://pypi.org/project/django-seal/1.4.1/
