### ISSUE TITLE
seal().prefetch_related() with one-to-many relationship executes duplicated query

### ISSUE THREAD

**Issue by renetta96** [charettes/django-seal#58]
I turned on Django query debug and found out that when I query like this:

```
models = list(Parent.objects.seal().prefetch_related("children").all()[0:10])
```

It outputs one duplicated query for the prefetch. If I remove seal(), it only outputs one query, which is as expected. 
Could you check this?

**Comment by renetta96** [comment]
I also confirm it's not a duplication in logger. I checked mySQL general log and it truly ran the prefetch query twice.

**Comment by charettes** [comment]
Hey @renetta96, could you provide the exact Django version you are testing against as well as the models definition.

**Comment by renetta96** [comment]
@charettes the new commit fixed the issue.

**Comment by renetta96** [comment]
btw, I'm using Django==3.1.5
