### ISSUE TITLE
1.4.2 breaking changes

### ISSUE THREAD

**Issue by qeternity** [charettes/django-seal#62]
Hi - I just wanted to flag that after hours of debugging we pinned down a regression today to an unpinned dep upgrade.

I will dig into tomorrow, but 1.4.2 breaks some of our code that previously worked perfectly on 1.4.1

**Comment by charettes** [comment]
@qeternity I'm also debugging a possible issue on my side, I already identified one that is fixed in 1.4.3a0 but there still something broken in one of our projects test suite.

**Comment by qeternity** [comment]
Thanks for the quick response. Sorry I can't be more helping, it's nearly 3am here and I need sleep.

Will see if I can lend some help tomorrow. Thanks for this project!

**Comment by charettes** [comment]
fwiw you can sleep knowing that I've identified the issue and a 1.4.3 should be released tomorrow with the appropriate tests. Just trying to write proper regressions tests right now.

**Comment by charettes** [comment]
@qeternity if you could confirm that the changes of #63 that are included in the [1.4.3a1 pre-release](https://pypi.org/project/django-seal/1.4.3a1/) address that'd be 💯 . I'll make sure to release 1.4.3 final tomorrow if it's the case. Sorry for all the trouble here 😅

**Comment by qeternity** [comment]
@charettes the 3a1 release does indeed seem to resolve our problems. I will stay pinned to 1.4.1 in the meantime but we will evaluate the 1.4.3 release and come back with any observations. Thanks again for your hard work!

**Comment by charettes** [comment]
Awesome, thanks for confirming. I'll close this issue for now then and release 1.4.3 later today.
