### ISSUE TITLE
Recommended approach to seal by default?

### ISSUE THREAD

**Issue by benhubsch** [charettes/django-seal#73]
I really like the functionality of this library and want to subclass a number of my existing models with `SealableModel`. However, I don't want to update each of their respective queries with the `seal()` call because there are a lot of callsites, and I'm also worried that the extra call will be too easily omitted in future callsites.

Is there a recommended approach for sealing all queries by default, so that I can get the sealing functionality for free with a standard `Blog.objects.filter/get` call? Thank you so much!

**Comment by charettes** [comment]
Hey @benhubsch, thanks for your feedback!

If the library allowed for passing a `seal: bool = False` argument at class and manager definition time would that suit your needs?

e.g.

```python
# class definition, all managers are sealed by default
class Blog(SealableModel, seal=True):
   ...

# manager definition
class Entry(SealableModel):
    objects = SealableQuerySet.as_manager(seal=True)
```

**Comment by benhubsch** [comment]
Yes, definitely would!

**Comment by charettes** [comment]
@benhubsch you can try it out on `django-seal==1.6.0`, let me know if you into any issues!
