### ISSUE TITLE
Possibility to use as a mixin?

### ISSUE THREAD

**Issue by YPCrumble** [charettes/django-seal#76]
Would it be possible to use a mixin that could implement the `SealableModel, seal=True` functionality? In particular I'm inheriting from django extensions' `TimeStampedModel` for a few models that I'd like to try django-seal on.

Thanks for maintaining this repo!

**Comment by charettes** [comment]
Starting with 1.6.1 which was just released you should be able to define a reusable abstract class that fits your need

```python
class BaseModel(SealableModel, TimeStampedModel, seal=True):
    class Meta:
        abstract = True
```
