### ISSUE TITLE
[SUGGESTION] Add MyPy type hints

### ISSUE THREAD

**Issue by YPCrumble** [charettes/django-seal#79]
Thanks for maintaining this and thanks so much for #76 !!

My linter is complaining about the `seal=True` directive:

> Unexpected keyword argument "seal" for "__init_subclass__" of "object"

Another option might be to allow using a class attribute (or even add it to `Meta`):

```
class MyModel(SealableModel):
    seal=True
...
```

Making this compatible with MyPy would be very helpful. Thank you for considering it!

**Comment by charettes** [comment]
That's unfortunately a false positive of your linter, there's nothing invalid about how `SealableModel.__init_subclass__(seal)` is implemented.

If your linter bugs you with false positive `# type: ignore` is the answer.

**Comment by YPCrumble** [comment]
@charettes looks like you are 100% correct, it's a bug with MyPy: https://github.com/python/mypy/issues/11036

Thank you for your response!
